# Generated by Django 2.2.1 on 2019-05-27 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('createdAt', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('deadline', models.DateTimeField()),
            ],
        ),
    ]
