# Generated by Django 2.2.1 on 2019-05-31 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'items'},
        ),
    ]
